/*
 * File: app/store/StorePort.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.StorePort', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StorePort',
            data: [
                {
                    text: '任意',
                    value: '0'
                },
                {
                    text: 'FTP',
                    value: 21
                },
                {
                    text: 'SSH',
                    value: 22
                },
                {
                    text: 'Telnet',
                    value: 23
                },
                {
                    text: 'SMTP',
                    value: 25
                },
                {
                    text: 'DNS',
                    value: 53
                },
                {
                    text: 'HTTP',
                    value: 80
                },
                {
                    text: 'POP3',
                    value: 110
                },
                {
                    text: 'IMAP',
                    value: 143
                },
                {
                    text: 'HTTPS',
                    value: 443
                },
                {
                    text: 'SNMP(UDP)',
                    value: 161
                },
                {
                    text: 'SNMP(TCP)',
                    value: 191
                }
            ],
            fields: [
                {
                    name: 'text'
                },
                {
                    name: 'value'
                }
            ]
        }, cfg)]);
    }
});