/*
 * File: app/store/StoreUser.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.StoreUser', {
    extend: 'Ext.data.Store',

    requires: [
        'app.model.userModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StoreUser',
            model: 'app.model.userModel',
            data: [
                {
                    id: 26,
                    userName: 'provident',
                    password: 'zFGEjrHBLCI',
                    email: 'rsnyder@skajo.name',
                    createTime: '4/4/2007'
                },
                {
                    id: 54,
                    userName: 'provident',
                    password: 'IThjiM0w0eRO',
                    email: 'phayes@twitterbeat.info',
                    createTime: '1/8/2008'
                },
                {
                    id: 751,
                    userName: 'est',
                    password: 'I59OLvg',
                    email: 'rreed@gabspot.org',
                    createTime: '8/13/2006'
                },
                {
                    id: 377,
                    userName: 'laboriosam',
                    password: 'xwKGwKo47m',
                    email: 'jrussell@blogspan.com',
                    createTime: '6/23/2008'
                },
                {
                    id: 1,
                    userName: 'vel',
                    password: 'lSwDzR6CONi',
                    email: 'srose@viva.name',
                    createTime: '10/16/2004'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});