/*
 * File: app/store/StoreMask.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.store.StoreMask', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'StoreMask',
            data: [
                {
                    mask: 142
                },
                {
                    mask: 78
                },
                {
                    mask: 575
                },
                {
                    mask: 120
                },
                {
                    mask: 915
                },
                {
                    mask: 996
                },
                {
                    mask: 531
                },
                {
                    mask: 529
                },
                {
                    mask: 131
                },
                {
                    mask: 304
                }
            ],
            fields: [
                {
                    name: 'mask'
                }
            ]
        }, cfg)]);
    }
});