/*
 * File: app/view/DomainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.DomainView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.Domainview',

    requires: [
        'app.view.DomainViewViewModel',
        'app.view.PagingToolbar',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging',
        'Ext.grid.View',
        'Ext.tab.Tab',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'domainview'
    },
    title: '域名管理',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'gridpanel',
                    autoScroll: true,
                    margin: 10,
                    title: '域名列表',
                    autoLoad: true,
                    columnLines: false,
                    enableColumnHide: false,
                    scroll: 'none',
                    sortableColumns: false,
                    store: 'StoreZones',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: '70%',
                            dataIndex: 'Domain',
                            text: '域名'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'RecordCount',
                            text: '记录',
                            format: '0000'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (record.data.Enable==1)
                                return '<font color="#00FF00">正常解析</font>';
                                else
                                return '<font color="#FF0000">停止解析</font>';
                            },
                            text: '域名状态'
                        },
                        {
                            xtype: 'actioncolumn',
                            text: '操作',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var win = new Ext.create('app.view.DomainWindows');
                                        win.setzone(view.getStore().getAt(rowIndex).data);
                                        win.show();
                                    },
                                    altText: '',
                                    icon: 'image/edit.gif',
                                    tooltip: '编辑'
                                },
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var zone = view.getStore().getAt(rowIndex).data;
                                        var config = {
                                            title: "确认删除",
                                            msg: "请确认是否删除，删除后改域名下记录也将全部删除",
                                            closable: false,
                                            buttons: Ext.MessageBox.YESNO,
                                            icon: Ext.MessageBox.WARNING,
                                            fn: function(btn) {
                                                if (btn == "yes") {
                                                    Ext.Ajax.request({
                                                        url: '../zone/remove',
                                                        success: function(data, a1, a2) {
                                                            this.view.getStore().load();
                                                            var result = Ext.decode(data.responseText);
                                                            if (result.success) {
                                                                Ext.Msg.alert('成功', result.msg);
                                                            }
                                                        },
                                                        failure: function(data) {
                                                            Ext.Msg.alert('失败', "删除失败");
                                                        },
                                                        jsonData: {
                                                            Domain: this.zone.Domain
                                                        },
                                                        scope: {
                                                            zone: this.zone,
                                                            view: this.view
                                                        }
                                                    });
                                                }
                                            },
                                            scope: {
                                                zone: zone,
                                                view: view
                                            },
                                        };
                                        Ext.MessageBox.show(config, this);
                                    },
                                    icon: 'image/delete.gif',
                                    tooltip: '删除'
                                },
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var win = new Ext.create('app.view.RecordWindows');
                                        win.setzone(view.getStore().getAt(rowIndex).data);
                                        win.show();
                                    },
                                    icon: 'image/accept.png'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var win = new Ext.create('app.view.DomainWindows');
                                win.show();
                            },
                            text: '创建域名'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var config = {
                                    title: "确认删除",
                                    msg: "请确认应用设置，应用设置后更改的记录将生效",
                                    closable: false,
                                    buttons: Ext.MessageBox.YESNO,
                                    icon: Ext.MessageBox.WARNING,
                                    fn: function(btn) {
                                        if (btn == "yes") {
                                            Ext.Ajax.request({
                                                url: '../server/apply',
                                                success: function(data, a1, a2) {
                                                    var result = Ext.decode(data.responseText);
                                                    if (result.success) {
                                                        Ext.Msg.alert('成功', result.msg);
                                                    }
                                                },
                                                failure: function(data) {
                                                    Ext.Msg.alert('失败', "删除失败");
                                                },
                                                jsonData: {

                                                },
                                            });
                                        }
                                    },

                                };
                                Ext.MessageBox.show(config, this);
                            },
                            text: '应用设置'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'searchDomainName',
                            fieldLabel: 'Label',
                            hideLabel: true,
                            allowBlank: false
                        },
                        {
                            xtype: 'button',
                            itemId: 'search',
                            text: '搜索域名',
                            listeners: {
                                click: 'onSearchClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],

    onSearchClick: function(button, e, eOpts) {
        var me = this,
            grid = me.down("gridpanel"),
            store = grid.getStore(),
            proxy = store.getProxy(),
            searchDomainName = me.down("textfield#searchDomainName").getValue();
        if(searchDomainName){
            proxy.setExtraParam("s", searchDomainName);
            store.load();
        }
    }

});