/*
 * File: app/view/DomainAdd.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.DomainAdd', {
    extend: 'Ext.form.Panel',
    alias: 'widget.DomainAdd',

    requires: [
        'app.view.DomainAddViewModel',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    config: {
        RowUpdate: false,
        urlUpdate: '../zone/update'
    },

    viewModel: {
        type: 'domainadd'
    },
    padding: 20,
    bodyPadding: 10,
    header: false,
    title: '创建域名',
    jsonSubmit: true,
    url: '../zone/add',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'fieldset',
            border: 1,
            title: '基本选项',
            items: [
                {
                    xtype: 'textfield',
                    width: '',
                    fieldLabel: '输入域名',
                    name: 'Domain',
                    allowBlank: false
                },
                {
                    xtype: 'checkboxfield',
                    fieldLabel: '      ',
                    labelSeparator: ' ',
                    name: 'Enable',
                    value: 1,
                    boxLabel: '开启解析',
                    checked: true,
                    inputValue: '1',
                    uncheckedValue: '0'
                },
                {
                    xtype: 'checkboxfield',
                    itemId: 'domainSwitch',
                    fieldLabel: '  ',
                    labelSeparator: ' ',
                    name: 'DomainSwitched',
                    boxLabel: '域名转发',
                    listeners: {
                        change: 'onDomainSwitchChange'
                    }
                }
            ]
        },
        {
            xtype: 'fieldset',
            hidden: true,
            itemId: 'domainSwitchSet',
            title: '域名转发',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'IP1',
                    name: 'IP2',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'IP2',
                    name: 'IP2',
                    allowBlank: false
                }
            ]
        },
        {
            xtype: 'fieldset',
            title: '高级选项',
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    width: '',
                    fieldLabel: '序列号',
                    name: 'Serial',
                    allowBlank: false,
                    hideTrigger: true,
                    spinDownEnabled: false,
                    spinUpEnabled: false
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: '刷新时间 (秒)',
                    name: 'Refresh',
                    value: 28800,
                    allowBlank: false,
                    hideTrigger: true,
                    spinDownEnabled: false,
                    spinUpEnabled: false
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: '重试时间(秒)',
                    name: 'Retry',
                    value: 7200,
                    allowBlank: false,
                    hideTrigger: true,
                    spinDownEnabled: false,
                    spinUpEnabled: false
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: '过期时间(秒)',
                    name: 'Expire',
                    value: 604800,
                    allowBlank: false,
                    hideTrigger: true,
                    spinDownEnabled: false,
                    spinUpEnabled: false
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: '最小TTL',
                    name: 'MinimumTTL',
                    value: 3600,
                    allowBlank: false,
                    hideTrigger: true,
                    spinDownEnabled: false,
                    spinUpEnabled: false
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: '全局TTL:',
                    name: 'TTL',
                    value: 3600,
                    allowBlank: false,
                    hideTrigger: true,
                    spinDownEnabled: false,
                    spinUpEnabled: false
                }
            ]
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                var Valid = this.up("form").getForm().isValid();
                if (!Valid) return;

                var rowupdate = this.up("DomainAdd").RowUpdate;
                if (rowupdate)
                {
                    this.up("form").getForm().url=this.up("DomainAdd").urlUpdate;
                }
                this.up("form").getForm().submit({
                    waitMsg: '正在保存',
                    success: function (form, action) {
                        Ext.Msg.alert('成功', action.result.msg);
                    },
                    failure: function (form, action) {
                        Ext.Msg.alert('失败', action.result.msg);
                    }
                });
            },
            text: '保存'
        }
    ],

    onDomainSwitchChange: function(field, newValue, oldValue, eOpts) {
        var checked = field.getValue(),
            domainSwitchSet = this.down('#domainSwitchSet');
        if(checked){
            domainSwitchSet.show();
        }else{
            domainSwitchSet.hide();
        }
    }

});