/*
 * File: app/view/DomainWindows.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.DomainWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.DomainWindows',

    requires: [
        'app.view.DomainWindowsViewModel',
        'app.view.DomainAdd',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'domainwindows'
    },
    height: 510,
    width: 642,
    title: '域名管理',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'DomainAdd'
        }
    ],
    listeners: {
        beforeshow: 'onWindowBeforeShow',
        activate: 'onWindowActivate'
    },

    onWindowBeforeShow: function(component, eOpts) {
        if (this.down("DomainAdd").RowUpdate!==true)
          {
             this.down("DomainAdd").query("numberfield[name=Serial]")[0].setValue(Ext.util.Format.date(new Date(), "Ymd01"));
          }

    },

    onWindowActivate: function(window, eOpts) {
        this.down("DomainAdd").query("numberfield[name=Serial]")[0].value =Ext.util.Format.date(new Date(), "Ymd01");
    },

    setzone: function(zone) {
        this.down("DomainAdd").zone=zone;
        this.down("DomainAdd").RowUpdate=true;
        this.down("DomainAdd").query("textfield[name=Domain]")[0].readOnly=true;
        this.down("form").getForm().setValues(zone.data);
    }

});