/*
 * File: app/view/Generalconfig.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.Generalconfig', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.Generalconfig',

    requires: [
        'app.view.GeneralconfigViewModel',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Number',
        'Ext.toolbar.Spacer',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'generalconfig'
    },
    title: '常规设置',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch',
        padding: 10
    },
    items: [
        {
            xtype: 'panel',
            flex: 1,
            autoScroll: true,
            header: false,
            title: 'My Panel',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: '10 25',
                    header: false,
                    title: 'My Panel',
                    jsonSubmit: true,
                    url: '../system/config',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'name',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: '主机名称',
                                    name: 'HOST_NAME'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: '3 0 0 20',
                                    text: '这是服务器的名称，这里不要填写域名'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'domain',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: '域名',
                                    name: 'DOMAIN_NAME'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: '3 0 0 20',
                                    text: '指定域名，如fercase.com.cn'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'protocol',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    flex: 1,
                                    fieldLabel: 'WEB协议',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'WEB_PROTOCOL',
                                            boxLabel: 'HTTP',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'WEB_PROTOCOL',
                                            boxLabel: 'HTTPS',
                                            inputValue: '0'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: '3 0 0 20',
                                    text: '选择连接方式'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'port',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    fieldLabel: 'WEB端口',
                                    name: 'WEB_PORT'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: '3 0 0 20',
                                    text: '指定WEB访问端口'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'logintype',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    flex: 1,
                                    fieldLabel: '登录方式',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'LOGIN_TYPE',
                                            boxLabel: 'HTTP',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'LOGIN_TYPE',
                                            boxLabel: 'COOKIE',
                                            inputValue: '0'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'timesetting',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: '时间设置',
                                    name: 'TIME'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'timezone',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    fieldLabel: '选择时区',
                                    name: 'TIME_ZONE',
                                    store: 'StoreTimezone'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'timesync',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    fieldLabel: '时间同步',
                                    name: 'NTP'
                                },
                                {
                                    xtype: 'label',
                                    margin: '0 0 0 5',
                                    padding: '5 0',
                                    width: 15,
                                    text: '分钟'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: '3 0 0 5',
                                    text: '指定每次同步间隔时间，如果设置为0，则不同步时间，建议按默认（300）设置'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: 'timeserver',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: '时间服务器',
                                    name: 'NTP_SERVER'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    margin: '3 0 0 20',
                                    text: '指定从那里同步时间'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: '日志设置',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: '5 0'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            flex: 1,
                                            margin: '5 0 5',
                                            style: '{font-weight:bold;}',
                                            text: '启用日志'
                                        },
                                        {
                                            xtype: 'checkboxgroup',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    name: 'LOG_FIREWALL',
                                                    boxLabel: '防火墙日志'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name: 'LOG_DNS',
                                                    boxLabel: 'DNS日志'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name: 'LOG_SYSTEM',
                                                    boxLabel: '系统日志'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'label',
                                            hidden: true,
                                            style: '{font-weight:bold;}',
                                            text: '远程日志'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            hidden: true,
                                            fieldLabel: '服务器'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    fieldLabel: 'info',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            flex: 1,
                                            margin: '3 0 0 20',
                                            text: '输入远程存储日志的服务器，如果为空，则不启用远程日志服务'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'saveBtn',
                                    margin: '0 0 0 20',
                                    text: '保存',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onPanelBeforeRender'
    },

    onButtonClick: function(button, e, eOpts) {
        var me = this,
            form = me.down('form');
        form.submit({
            waitMsg: '正在保存',
            success: function (form, action) {
                Ext.Msg.alert('成功', '保存成功');
            },
            failure: function (form, action) {
                Ext.Msg.alert('失败',  action.result.msg);
            }
        });
    },

    onPanelBeforeRender: function(component, eOpts) {
        var store = Ext.data.StoreManager.get('General'),
            form = this.down('form').getForm();
        store.load({
            scope: this,
            callback: function(records, options, success){
                if(success){
                    var record = records[0];
                    form.setValues(record.getData());
                }
            }

        });

    }

});