/*
 * File: app/view/ImportAndExport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.ImportAndExport', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.importandexport',

    requires: [
        'app.view.ImportAndExportViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'importandexport'
    },
    title: '导入导出',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            layout: {
                type: 'hbox',
                padding: 10
            },
            items: [
                {
                    xtype: 'button',
                    margin: '0 50 0 0',
                    padding: '5 15',
                    text: '导入',
                    listeners: {
                        click: 'onImportClick'
                    }
                },
                {
                    xtype: 'button',
                    padding: '5 15',
                    text: '导出',
                    listeners: {
                        click: 'onExportClick'
                    }
                }
            ]
        }
    ],

    onImportClick: function(button, e, eOpts) {
        this.openUrl('http://120.27.34.89:8090/zones/import');
    },

    onExportClick: function(button, e, eOpts) {
        this.openUrl('http://120.27.34.89:8090/zones/export', '_self');
    },

    openUrl: function(href, target) {
        if(!this.aTag){
            this.aTag = document.createElement('a');
        }
        var aTag = this.aTag;
        aTag.setAttribute('href', href);
        aTag.setAttribute('target', target | '_blank');
        if(document.all){// IE浏览器
            aTag.setAttribute('style', 'display: none;');
            document.body.appendChild(aTag);
        }
        if(aTag.click){
            aTag.click();
        }else if(aTag.fireEvent){
            aTag.fireEvent('onclick');
        }else{
            var ev = document.createEvent('HTMLEvents');
            ev.initEvent('click', false, true);
            aTag.dispatchEvent(ev);
        }
    }

});