/*
 * File: app/view/OperateLogView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.OperateLogView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.OperateLogView',

    requires: [
        'app.view.OperateLogViewViewModel',
        'app.view.PagingToolbar',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'operatelogview'
    },
    title: '操作日志',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'dnsloggrid1',
            header: false,
            title: 'My Grid Panel',
            autoLoad: true,
            scroll: 'vertical',
            store: 'StoreDNSLog',
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: '5%',
                    dataIndex: 'ID',
                    text: '行号',
                    format: '0000'
                },
                {
                    xtype: 'gridcolumn',
                    width: '95%',
                    dataIndex: 'LOG',
                    text: '日志'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    store: 'StoreDNSLog',
                    dock: 'bottom'
                }
            ]
        }
    ],
    listeners: {
        beforeactivate: 'onPanelBeforeActivate'
    },

    onPanelBeforeActivate: function(component, eOpts) {
        this.query("gridpanel[id=dnsloggrid]")[0].store.load();
    }

});