/*
 * File: app/view/RecordWindows.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.RecordWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.RecordWindows',

    requires: [
        'app.view.RecordWindowsViewModel',
        'app.view.RecordView',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'recordwindows'
    },
    height: 605,
    width: 818,
    layout: 'fit',
    title: '纪录管理',

    items: [
        {
            xtype: 'RecordView'
        }
    ],

    setzone: function(zone) {
        var store = this.down("RecordView").query("gridpanel")[0].store;
        this.down("RecordView").query("displayfield[name=domain]")[0].setValue(zone.Domain);
        this.down("RecordView").query("hiddenfield[name=ZoneID]")[0].setValue(zone.ID);
        store.getProxy().setExtraParam('zone', zone.ID);
        store.load()
    }

});