/*
 * File: app/view/RoutemgrView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.RoutemgrView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.RoutemgrView',

    requires: [
        'app.view.RoutemgrViewViewModel',
        'app.view.PagingToolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox'
    ],

    config: {
        rowUpdate: false,
        urlUpdate: '../route/update'
    },

    viewModel: {
        type: 'routemgrview'
    },
    title: '路由管理',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: '路由列表',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            autoScroll: true,
                            itemId: 'routeList',
                            header: false,
                            title: 'routeList',
                            autoLoad: true,
                            scroll: 'vertical',
                            store: 'StoreRoute',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: '10%',
                                    dataIndex: 'route',
                                    text: '名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'eth',
                                    text: '网卡'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '20%',
                                    dataIndex: 'address',
                                    text: '网络地址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '20%',
                                    dataIndex: 'gateway',
                                    text: '网关地址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if(record.data.enabled == 1){
                                            return '<a href="#" class="enable">启用</a>';
                                        }else{
                                            return '<a href="#" class="disable">停用</a>';
                                        }
                                    },
                                    dataIndex: 'enabled',
                                    text: '状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'memo',
                                    text: '备注'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    text: '操作',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                console.log('a');
                                                var tabpanel = view.up('tabpanel'),
                                                    routeAddForm = tabpanel.down("form#routeAddForm"),
                                                    panel = tabpanel.up("panel");
                                                panel.rowUpdate = true;
                                                routeAddForm.getForm().setValues(record.data);
                                                routeAddForm.down("textfield[name=route]").setDisabled(true);
                                                tabpanel.setActiveItem(1);
                                            },
                                            altText: '修改',
                                            icon: 'image/edit.gif',
                                            tooltip: '修改'
                                        },
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                var route = record.data;
                                                var confirm = {
                                                    title: "确认删除",
                                                    msg: "请确认是否删除这个路由",
                                                    closable: false,
                                                    buttons: Ext.MessageBox.YESNO,
                                                    icon: Ext.MessageBox.WARNING,
                                                    fn: function(btn) {
                                                        if (btn == "yes") {
                                                            Ext.Ajax.request({
                                                                url: '../route/remove',
                                                                success: function(data, a1, a2) {
                                                                    view.getStore().load();
                                                                    var result = Ext.decode(data.responseText);
                                                                    if (result.success) {
                                                                        Ext.Msg.alert('成功', result.msg);
                                                                    }
                                                                },
                                                                failure: function(data) {
                                                                    Ext.Msg.alert('失败', "删除失败");
                                                                },
                                                                jsonData: {
                                                                    id: this.route.id
                                                                },
                                                                scope: {
                                                                    route: this.route,
                                                                    view: this.view
                                                                }
                                                            });
                                                        }
                                                    },
                                                    scope: {
                                                        route: route,
                                                        view: view
                                                    }
                                                };
                                                Ext.MessageBox.show(confirm, this);
                                            },
                                            altText: '删除',
                                            icon: 'image/delete.gif',
                                            tooltip: '删除'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    store: 'StoreRoute',
                                    dock: 'bottom'
                                }
                            ],
                            listeners: {
                                cellclick: 'onRouteListCellClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '添加路由',
                    items: [
                        {
                            xtype: 'form',
                            itemId: 'routeAddForm',
                            bodyPadding: 10,
                            header: false,
                            jsonSubmit: true,
                            url: '../route/add',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    anchor: '60%',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '60%',
                                    fieldLabel: '路由名称',
                                    name: 'route',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '60%',
                                    fieldLabel: '选择网卡',
                                    name: 'eth',
                                    disableKeyFilter: true,
                                    editable: false,
                                    displayField: 'name',
                                    store: 'StoreEth',
                                    valueField: 'name'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 30,
                                    layout: 'hbox',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '网络地址',
                                            name: 'ip'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '0 0 0 5',
                                            width: 60,
                                            fieldLabel: ' /',
                                            labelSeparator: '/',
                                            labelWidth: 5,
                                            name: 'mask',
                                            disableKeyFilter: true,
                                            editable: false,
                                            displayField: 'mask',
                                            store: 'StoreMask',
                                            valueField: 'mask'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '60%',
                                    modelValidation: false,
                                    fieldLabel: '网关',
                                    name: 'gateway',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '60%',
                                    fieldLabel: '描述',
                                    name: 'memo'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    fieldLabel: '生效设置',
                                    name: 'enabled',
                                    boxLabel: '立即启用'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    layout: {
                                        type: 'hbox',
                                        align: 'bottom'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'save',
                                            text: '保存',
                                            listeners: {
                                                click: 'onSaveClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'cancel',
                                            margin: '0 0 0 50',
                                            text: '取消',
                                            listeners: {
                                                click: 'onCancelClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        deactivate: 'onPanelDeactivate'
                    }
                }
            ]
        }
    ],

    onRouteListCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var target = e.target,
            route = record.data,
            enabled = 0;
        if(target && target.className.indexOf("disable") != -1){
            enabled = 1;
        }else if(target && target.className.indexOf("enable") != -1){
            enabled = 0;
        }else{
            return false;
        }
        Ext.Ajax.request({
            url: '../route/status',
            success: function(data, a1, a2) {

                var result = Ext.decode(data.responseText);
                if (result.success) {
                    this.route.enabled = this.enabled;
                    this.view.refresh();
                }
            },
            failure: function(data) {
                Ext.Msg.alert('失败', "操作失败");
            },
            jsonData: {
                id: route.id,
                enabled: enabled
            },
            scope: {
                route: route,
                enabled: enabled,
                view: tableview
            }
        });
    },

    onSaveClick: function(button, e, eOpts) {
         var me = this,
             form = me.down('form#routeAddForm'),
             valid = form.isValid();
        if(!valid){
            return false;
        }
        if(me.rowUpdate){
            form.getForm().url = me.urlUpdate;
        }
        form.submit({
            waitMsg: '正在保存',
            success: function (form, action) {
                Ext.Msg.alert('成功', '路由保存成功');

                if(me.rowUpdate){
                    me.down("pagingtoolbar").doRefresh();
                }else{
                    me.down("gridpanel#routeList").getStore().load();
                }
                me.resetForm();

            },
            failure: function (form, action) {
                Ext.Msg.alert('失败',  action.result.msg);
            }
        });
    },

    onCancelClick: function(button, e, eOpts) {
        this.resetForm();
    },

    onPanelDeactivate: function(component, eOpts) {
        this.resetForm();
    },

    resetForm: function() {
        var me = this,
            tabpanel = me.down("tabpanel"),
            routeAddForm = me.down("form#routeAddForm");
        tabpanel.setActiveItem(0);
        routeAddForm.down("textfield[name=route]").setDisabled(false);
        routeAddForm.reset();
    }

});