/*
 * File: app/view/RoutemgrView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.RoutemgrView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.RoutemgrView',

    requires: [
        'app.view.RoutemgrViewViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox'
    ],

    viewModel: {
        type: 'routemgrview'
    },
    title: '路由管理',

    items: [
        {
            xtype: 'tabpanel',
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: '路由列表'
                },
                {
                    xtype: 'panel',
                    title: '添加路由',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '60%',
                                    fieldLabel: '路由名称'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '60%',
                                    fieldLabel: '选择网卡'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 30,
                                    layout: 'hbox',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: '网络地址'
                                        },
                                        {
                                            xtype: 'combobox',
                                            padding: 10,
                                            fieldLabel: '        /',
                                            labelPad: 10,
                                            labelSeparator: ' ',
                                            labelWidth: 10
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '60%',
                                    fieldLabel: '描述'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    fieldLabel: '生效设置',
                                    boxLabel: '立即启用'
                                },
                                {
                                    xtype: 'button',
                                    text: '添加'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});