/*
 * File: app/view/SecuritymgrView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.SecuritymgrView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SecuritymgrView',

    requires: [
        'app.view.SecuritymgrViewViewModel',
        'app.view.PagingToolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.Checkbox',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea'
    ],

    config: {
        rowUpdate: false,
        urlUpdate: '../firewall/save'
    },

    viewModel: {
        type: 'securitymgrview'
    },
    title: '安全管理',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: '规则列表',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            autoScroll: true,
                            itemId: 'ruleList',
                            header: false,
                            title: 'ruleList',
                            autoLoad: true,
                            store: 'StoreRules',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var storeConnector = Ext.data.StoreManager.get('StoreConnector'),
                                            record = storeConnector.findRecord('value', value);
                                        return record ? record.get('key') : value;
                                    },
                                    width: '10%',
                                    dataIndex: 'interface',
                                    text: '网络接口'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '20%',
                                    dataIndex: 'source',
                                    text: '来源地址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '20%',
                                    dataIndex: 'target',
                                    text: '目标地址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'protocol',
                                    text: '协议'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'direction',
                                    text: '方向'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'action',
                                    text: '执行属性'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if(record.data.enable == 1){
                                            return '<a href="#" class="enable">启用</a>';
                                        }else{
                                            return '<a href="#" class="disable">停用</a>';
                                        }
                                    },
                                    dataIndex: 'enabled',
                                    text: '状态'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    text: '操作',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                var tabpanel = view.up('tabpanel'),
                                                    ruleAddForm = tabpanel.down("form#ruleAddForm"),
                                                    panel = tabpanel.up("panel");
                                                panel.rowUpdate = true;
                                                ruleAddForm.getForm().setValues(record.data);
                                                tabpanel.setActiveItem(1);
                                            },
                                            altText: '修改',
                                            icon: 'image/edit.gif',
                                            tooltip: '修改'
                                        },
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                var rule = record.data;
                                                var confirm = {
                                                    title: "确认删除",
                                                    msg: "请确认是否删除这个规则？",
                                                    closable: false,
                                                    buttons: Ext.MessageBox.YESNO,
                                                    icon: Ext.MessageBox.WARNING,
                                                    fn: function(btn) {
                                                        if (btn == "yes") {
                                                            Ext.Ajax.request({
                                                                url: '../firewall/remove',
                                                                success: function(data, a1, a2) {
                                                                    view.getStore().load();
                                                                    var result = Ext.decode(data.responseText);
                                                                    if (result.success) {
                                                                        Ext.Msg.alert('成功', result.msg);
                                                                    }
                                                                },
                                                                failure: function(data) {
                                                                    Ext.Msg.alert('失败', "删除失败");
                                                                },
                                                                jsonData: {
                                                                    id: this.rule.id
                                                                },
                                                                scope: {
                                                                    rule: this.rule,
                                                                    view: this.view
                                                                }
                                                            });
                                                        }
                                                    },
                                                    scope: {
                                                        rule: rule,
                                                        view: view
                                                    }
                                                };
                                                Ext.MessageBox.show(confirm, this);
                                            },
                                            altText: '删除',
                                            icon: 'image/delete.gif',
                                            tooltip: '删除'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    store: 'StoreRules',
                                    dock: 'bottom'
                                }
                            ],
                            listeners: {
                                cellclick: 'onRuleListCellClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: '添加规则',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            autoScroll: true,
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'form',
                                    itemId: 'ruleAddForm',
                                    bodyPadding: 10,
                                    header: false,
                                    jsonSubmit: true,
                                    url: '../firewall/add',
                                    items: [
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'forbidrule',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    width: 400,
                                                    fieldLabel: '启动规则',
                                                    name: 'enable',
                                                    boxLabel: '启动规则',
                                                    inputValue: '1',
                                                    uncheckedValue: '0'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    margin: '3 0 0 20',
                                                    text: '选中后，这条规则将会生效'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            hidden: true,
                                            fieldLabel: 'ipversion',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'IP版本',
                                                    submitValue: false
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'actionproperty',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    maxHeight: 20,
                                                    width: 400,
                                                    fieldLabel: '执行属性',
                                                    name: 'action',
                                                    store: 'StoreAction',
                                                    valueField: 'value'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    html: 'block表示如果规则与包匹配，则丢弃包。<br>pass表示如果规则与包匹配，则允许包通过防火墙。',
                                                    margin: '3 0 0 20'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'ruledirection',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    maxHeight: 20,
                                                    width: 400,
                                                    fieldLabel: '规则方向',
                                                    name: 'direction',
                                                    store: 'StoreDirection',
                                                    valueField: 'value'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    html: 'in表示规则应被应用于刚刚从Internet公网上收到的数据包。<br>out表示规则应被用于即发出到Internet的数据包。',
                                                    margin: '3 0 0 20'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'selectinterface',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    margin: '5 0',
                                                    maxHeight: 20,
                                                    width: 400,
                                                    fieldLabel: '选择接口',
                                                    name: 'interface',
                                                    autoLoadOnValue: true,
                                                    displayField: 'key',
                                                    store: 'StoreConnector',
                                                    valueField: 'value'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    margin: '3 0 0 20',
                                                    text: '规则只会应用到选定的一个网络接口上的出入数据包上。'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'selectprotocol',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    margin: '5 0',
                                                    maxHeight: 20,
                                                    width: 400,
                                                    fieldLabel: '选择协议',
                                                    name: 'protocol',
                                                    forceSelection: true,
                                                    store: 'StoreProtocol',
                                                    valueField: 'value'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    margin: '3 0 0 20',
                                                    text: '这里选择规则匹配某个特定的协议。TCP/UDP可以同时匹配TCP或UDP包，避免过多重复规则。'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '来源地址',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 295,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            itemId: 'sourceAddr',
                                                            fieldLabel: 'Label',
                                                            hideLabel: true,
                                                            name: 'source_address',
                                                            editable: false,
                                                            autoLoadOnValue: true,
                                                            store: 'StoreAddress',
                                                            valueField: 'value',
                                                            listeners: {
                                                                select: 'onSourceAddrSelect',
                                                                afterrender: 'onSourceAddrAfterRender'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            fieldLabel: 'Label',
                                                            hideLabel: true,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    name: 'source_ip',
                                                                    regex: /^((25[0-5]|2[0-4]\d|[01]?\d\d?)($|(?!\.$)\.)){4}$/
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    margin: '0 0 0 5',
                                                                    width: 100,
                                                                    fieldLabel: '   /',
                                                                    labelSeparator: '/',
                                                                    labelWidth: 5,
                                                                    name: 'source_mask',
                                                                    maxValue: 128,
                                                                    minValue: 0
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    html: '选择或填写来源地址。单一主机，则是指定的一个IP地址掩码是32（255.255.255.255）。<br>子网络，则是指定一个子网，掩码是0-31。<br>如果是任意地址，则不需要填写IP和选择掩码。',
                                                    margin: '3 0 0 20'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '来源端口',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 295,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            itemId: 'selectSourcePort',
                                                            fieldLabel: '选择常用端口',
                                                            submitValue: false,
                                                            editable: false,
                                                            store: 'StorePort',
                                                            valueField: 'value',
                                                            listeners: {
                                                                select: 'onSourcePortSelect'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            fieldLabel: '自定义端口',
                                                            name: 'source_port',
                                                            maxValue: 65535,
                                                            minValue: 0
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    html: '填写自定义端口，如果填写了自定义端口，前面选择的常用端口将不起作用。<br>可以指定一个端口范围，如9999到65535端口：9999：65535',
                                                    margin: '3 0 0 20'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '目标地址',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 295,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            itemId: 'targetAddr',
                                                            fieldLabel: 'Label',
                                                            hideLabel: true,
                                                            name: 'target_address',
                                                            editable: false,
                                                            store: 'StoreAddress',
                                                            valueField: 'value',
                                                            listeners: {
                                                                select: 'onTargetAddrSelect',
                                                                afterrender: 'onTargetAddrAfterRender'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            width: 400,
                                                            fieldLabel: 'Label',
                                                            hideLabel: true,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    name: 'target_ip'
                                                                },
                                                                {
                                                                    xtype: 'numberfield',
                                                                    margin: '0 0 0 5',
                                                                    width: 100,
                                                                    fieldLabel: '   /',
                                                                    labelSeparator: '/',
                                                                    labelWidth: 5,
                                                                    name: 'target_mask',
                                                                    maxValue: 128,
                                                                    minValue: 0
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    html: '选择或填写目标地址。单一主机，则是指定的一个IP地址掩码是32（255.255.255.255）。<br>子网络，则是指定一个子网，掩码是0-31。<br>如果是任意地址，则不需要填写IP和选择掩码。',
                                                    margin: '3 0 0 20'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '目标端口',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 295,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            fieldLabel: '选择常用端口',
                                                            submitValue: false,
                                                            editable: false,
                                                            store: 'StorePort',
                                                            valueField: 'value',
                                                            listeners: {
                                                                select: 'onTargetPortSelect'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            fieldLabel: '自定义端口',
                                                            name: 'target_port',
                                                            maxValue: 65535,
                                                            minValue: 0
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    html: '填写自定义端口，如果填写了自定义端口，前面选择的常用端口将不起作用。<br>可以指定一个端口范围，如9999到65535端口：9999：65535',
                                                    margin: '3 0 0 20'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            hidden: true,
                                            fieldLabel: 'chip',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    width: 400,
                                                    fieldLabel: '碎片选型',
                                                    name: 'filter',
                                                    submitValue: false,
                                                    boxLabel: '碎片过滤',
                                                    inputValue: '1',
                                                    uncheckedValue: '0'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            hidden: true,
                                            fieldLabel: 'log',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    width: 400,
                                                    fieldLabel: '日志选项',
                                                    name: 'log',
                                                    submitValue: false,
                                                    boxLabel: '为该规则记录日志',
                                                    inputValue: '1',
                                                    uncheckedValue: '0'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    margin: '3 0 0 20',
                                                    text: '表示将与规则匹配的数据包头写入到ipl日志。'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'ruledescription',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    width: 400,
                                                    fieldLabel: '规则描述',
                                                    name: 'describe'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    margin: '3 0 0 20',
                                                    text: '简单描述该规则的用途或者其他说明'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            layout: {
                                                type: 'hbox',
                                                align: 'bottom'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'add',
                                                    text: '保存',
                                                    listeners: {
                                                        click: 'onAddClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        deactivate: 'onPanelDeactivate'
                    }
                }
            ]
        }
    ],

    onRuleListCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var target = e.target,
            rule = record.data,
            enable = 0;
        if(target.className.indexOf("disable") != -1){
            enable = 1;
        }else if(target.className.indexOf("enable") != -1){
            enable = 0;
        }else{
            return false;
        }
        Ext.Ajax.request({
            url: '../firewall/enable',
            success: function(data, a1, a2) {

                var result = Ext.decode(data.responseText);
                if (result.success) {
                    this.rule.enable = this.enable;
                    this.view.refresh();
                }
            },
            failure: function(data) {
                Ext.Msg.alert('失败', "操作失败");
            },
            jsonData: {
                id: rule.id,
                enable: enable
            },
            scope: {
                rule: rule,
                enable: enable,
                view: tableview
            }
        });
    },

    onSourceAddrSelect: function(combo, records, eOpts) {
        var ip = this.down('textfield[name=source_ip]'),
            mask = this.down('numberfield[name=source_mask]'),
            value = records && records[0] && records[0].getData() && records[0].getData().value || 0;
        if(0 === value){
            ip.setDisabled(true);
            mask.setDisabled(true);
            ip.setValue('');
            mask.setValue();
        }else if(1 === value){
            ip.setDisabled(false);
            mask.setDisabled(false);
        }else if(2 === value){
            ip.setDisabled(false);
            mask.setDisabled(false);
            mask.setValue(24);
        }
    },

    onSourceAddrAfterRender: function(component, eOpts) {
        component.select(0);
        component.fireEvent('select');
    },

    onSourcePortSelect: function(combo, records, eOpts) {
        var port = this.down('numberfield[name=source_port]'),
            value = records && records[0] && records[0].getData() && records[0].getData().value || 0;
            port.setValue(value);
    },

    onTargetAddrSelect: function(combo, records, eOpts) {
        var ip = this.down('textfield[name=target_ip]'),
            mask = this.down('numberfield[name=target_mask]'),
            value = records && records[0] && records[0].getData() && records[0].getData().value || 0;
        if(0 === value){
            ip.setDisabled(true);
            mask.setDisabled(true);
            ip.setValue('');
            mask.setValue();
        }else if(1 === value){
            ip.setDisabled(false);
            mask.setDisabled(false);
        }else if(2 === value){
            ip.setDisabled(false);
            mask.setDisabled(false);
            mask.setValue(24);
        }
    },

    onTargetAddrAfterRender: function(component, eOpts) {
        component.select(0);
        component.fireEvent('select');
    },

    onTargetPortSelect: function(combo, records, eOpts) {
        var port = this.down('numberfield[name=target_port]'),
            value = records && records[0] && records[0].getData() && records[0].getData().value || 0;
            port.setValue(value);
    },

    onAddClick: function(button, e, eOpts) {
         var me = this,
             form = me.down('form#ruleAddForm'),
             valid = form.isValid();
        if(!valid){
            return false;
        }
        if(me.rowUpdate){
            form.getForm().url = me.urlUpdate;
        }
        form.submit({
            waitMsg: '正在保存',
            success: function (form, action) {
                Ext.Msg.alert('成功', '保存成功');

                if(me.rowUpdate){
                    me.down("pagingtoolbar").doRefresh();
                }else{
                    me.down("gridpanel#ruleList").getStore().load();
                }
                me.resetForm();

            },
            failure: function (form, action) {
                Ext.Msg.alert('失败',  action.result.msg);
            }
        });
    },

    onPanelDeactivate: function(component, eOpts) {
        this.resetForm();
    },

    resetForm: function() {
        var me = this,
            tabpanel = me.down("tabpanel"),
            ruleAddForm = me.down("form#ruleAddForm");
        tabpanel.setActiveItem(0);
        ruleAddForm.reset();
    }

});