/*
 * File: app/view/SecuritymgrView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.SecuritymgrView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SecuritymgrView',

    requires: [
        'app.view.SecuritymgrViewViewModel',
        'app.view.PagingToolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.Checkbox',
        'Ext.form.Label',
        'Ext.form.field.ComboBox'
    ],

    config: {
        rowUpdate: false,
        urlUpdate: '../route/update'
    },

    viewModel: {
        type: 'securitymgrview'
    },
    title: '安全管理',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: '规则列表',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            autoScroll: true,
                            itemId: 'ruleList',
                            header: false,
                            title: 'routeList',
                            autoLoad: true,
                            store: 'StoreRoute',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    text: 'ID'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '10%',
                                    dataIndex: 'route',
                                    text: '网站接口'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'eth',
                                    text: '来源地址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '20%',
                                    dataIndex: 'address',
                                    text: '目标地址'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: '20%',
                                    dataIndex: 'gateway',
                                    text: '协议/版本'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if(record.data.enabled == 1){
                                            return '<a href="#" class="enable">启用</a>';
                                        }else{
                                            return '<a href="#" class="disable">停用</a>';
                                        }
                                    },
                                    dataIndex: 'enabled',
                                    text: '方向'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'memo',
                                    text: '执行属性'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if(record.data.enabled == 1){
                                            return '<a href="#" class="enable">启用</a>';
                                        }else{
                                            return '<a href="#" class="disable">停用</a>';
                                        }
                                    },
                                    dataIndex: 'enabled',
                                    text: '日志'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if(record.data.enabled == 1){
                                            return '<a href="#" class="enable">启用</a>';
                                        }else{
                                            return '<a href="#" class="disable">停用</a>';
                                        }
                                    },
                                    dataIndex: 'enabled',
                                    text: '状态'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    text: '操作',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                console.log('a');
                                                var tabpanel = view.up('tabpanel'),
                                                    routeAddForm = tabpanel.down("form#routeAddForm"),
                                                    panel = tabpanel.up("panel");
                                                panel.rowUpdate = true;
                                                routeAddForm.getForm().setValues(record.data);
                                                routeAddForm.down("textfield[name=route]").setDisabled(true);
                                                tabpanel.setActiveItem(1);
                                            },
                                            altText: '修改',
                                            icon: 'image/edit.gif',
                                            tooltip: '修改'
                                        },
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                var route = record.data;
                                                var confirm = {
                                                    title: "确认删除",
                                                    msg: "请确认是否删除这个路由",
                                                    closable: false,
                                                    buttons: Ext.MessageBox.YESNO,
                                                    icon: Ext.MessageBox.WARNING,
                                                    fn: function(btn) {
                                                        if (btn == "yes") {
                                                            Ext.Ajax.request({
                                                                url: '../route/remove',
                                                                success: function(data, a1, a2) {
                                                                    view.getStore().load();
                                                                    var result = Ext.decode(data.responseText);
                                                                    if (result.success) {
                                                                        Ext.Msg.alert('成功', result.msg);
                                                                    }
                                                                },
                                                                failure: function(data) {
                                                                    Ext.Msg.alert('失败', "删除失败");
                                                                },
                                                                jsonData: {
                                                                    id: this.route.id
                                                                },
                                                                scope: {
                                                                    route: this.route,
                                                                    view: this.view
                                                                }
                                                            });
                                                        }
                                                    },
                                                    scope: {
                                                        route: route,
                                                        view: view
                                                    }
                                                };
                                                Ext.MessageBox.show(confirm, this);
                                            },
                                            altText: '删除',
                                            icon: 'image/delete.gif',
                                            tooltip: '删除'
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    store: 'StoreRoute',
                                    dock: 'bottom'
                                }
                            ],
                            listeners: {
                                cellclick: 'onRouteListCellClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: '添加规则',
                    items: [
                        {
                            xtype: 'panel',
                            autoScroll: true,
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'form',
                                    itemId: 'ruleAddForm',
                                    bodyPadding: 10,
                                    header: false,
                                    jsonSubmit: true,
                                    url: '../route/add',
                                    items: [
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'forbidrule',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 1,
                                                    fieldLabel: '禁止规则',
                                                    boxLabel: '禁止规则'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    text: '选中后，这条规则将不会生效'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'ipversion',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'IP版本'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'actionproperty',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '执行属性'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'ruledirection',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '规则方向'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'selectinterface',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '选择接口'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'selectprotocol',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '选择协议'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '来源地址',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            fieldLabel: 'Label',
                                                            hideLabel: true
                                                        },
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            flex: 1,
                                                            width: 400,
                                                            fieldLabel: 'Label',
                                                            hideLabel: true,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield'
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    margin: '0 0 0 5',
                                                                    width: 60,
                                                                    fieldLabel: '   /',
                                                                    labelSeparator: '/',
                                                                    labelWidth: 5
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '来源端口',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            fieldLabel: '选择常用端口'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            fieldLabel: '自定义端口'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '目标地址',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            fieldLabel: 'Label',
                                                            hideLabel: true
                                                        },
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            flex: 1,
                                                            width: 400,
                                                            fieldLabel: 'Label',
                                                            hideLabel: true,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield'
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    margin: '0 0 0 5',
                                                                    width: 60,
                                                                    fieldLabel: '   /',
                                                                    labelSeparator: '/',
                                                                    labelWidth: 5
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '目标端口',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 1,
                                                            fieldLabel: '选择常用端口'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            fieldLabel: '自定义端口'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'chip',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 1,
                                                    fieldLabel: '碎片选型',
                                                    boxLabel: '碎片过滤'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    text: '选中后，这条规则将不会生效'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'log',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 1,
                                                    fieldLabel: '日志选项',
                                                    boxLabel: '为该规则记录日志'
                                                },
                                                {
                                                    xtype: 'label',
                                                    flex: 1,
                                                    text: '选中后，这条规则将不会生效'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: 'ruledescription',
                                            hideLabel: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: '规则描述'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            layout: {
                                                type: 'hbox',
                                                align: 'bottom'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'add',
                                                    text: '添加',
                                                    listeners: {
                                                        click: 'onAddClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        deactivate: 'onPanelDeactivate'
                    }
                }
            ]
        }
    ],

    onRouteListCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var target = e.target,
            route = record.data,
            enabled = 0;
        if(target && target.className.indexOf("disable") != -1){
            enabled = 1;
        }
        Ext.Ajax.request({
            url: '../route/status',
            success: function(data, a1, a2) {

                var result = Ext.decode(data.responseText);
                if (result.success) {
                    this.route.enabled = this.enabled;
                    this.view.refresh();
                }
            },
            failure: function(data) {
                Ext.Msg.alert('失败', "操作失败");
            },
            jsonData: {
                id: route.id,
                enabled: enabled
            },
            scope: {
                route: route,
                enabled: enabled,
                view: tableview
            }
        });
    },

    onAddClick: function(button, e, eOpts) {
         var me = this,
             form = me.down('form#ruleAddForm'),
             valid = form.isValid();
        if(!valid){
            return false;
        }
        if(me.rowUpdate){
            form.getForm().url = me.urlUpdate;
        }
        form.submit({
            waitMsg: '正在保存',
            success: function (form, action) {
                Ext.Msg.alert('成功', '路由保存成功');

                if(me.rowUpdate){
                    me.down("pagingtoolbar").doRefresh();
                }else{
                    me.down("gridpanel#ruleList").getStore().load();
                }
                me.resetForm();

            },
            failure: function (form, action) {
                Ext.Msg.alert('失败',  action.result.msg);
            }
        });
    },

    onPanelDeactivate: function(component, eOpts) {
        this.resetForm();
    },

    resetForm: function() {
        var me = this,
            tabpanel = me.down("tabpanel"),
            ruleAddForm = me.down("form#ruleAddForm");
        //tabpanel.setActiveItem(0);
        //routeAddForm.down("textfield[name=route]").setDisabled(false);
        //routeAddForm.reset();
    }

});