/*
 * File: app/view/StatisticsView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.StatisticsView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.statisticsview',

    requires: [
        'app.view.StatisticsViewViewModel',
        'app.view.PagingToolbar',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'statisticsview'
    },
    title: '查询统计',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'statisticsgrid',
            header: false,
            title: 'My Grid Panel',
            autoLoad: true,
            scroll: 'vertical',
            store: 'StoreStatistics',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: '20%',
                    dataIndex: 'name',
                    text: '名称'
                },
                {
                    xtype: 'gridcolumn',
                    width: '80%',
                    dataIndex: 'count',
                    text: '数量'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    store: 'StoreStatistics',
                    dock: 'bottom'
                }
            ]
        }
    ],
    listeners: {
        beforeactivate: 'onPanelBeforeActivate'
    },

    onPanelBeforeActivate: function(component, eOpts) {
        this.query("gridpanel[id=statisticsgrid]")[0].store.load();
    }

});