/*
 * File: app/view/SystemInfoView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.SystemInfoView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SystemInfoView',

    requires: [
        'app.view.SystemInfoViewViewModel',
        'app.view.TrafficView',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'app.store.StoreSystemInfo'
    ],

    viewModel: {
        type: 'systeminfoview'
    },
    margin: '',
    title: '系统信息',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: '系统信息',
                    items: [
                        {
                            xtype: 'form',
                            margin: 10,
                            bodyPadding: 10,
                            title: '系统资源',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: 'CPU使用率',
                                    name: 'cpu',
                                    value: '-'
                                },
                                {
                                    xtype: 'displayfield',
                                    anchor: '100%',
                                    fieldLabel: '内存',
                                    name: 'memorydisplay',
                                    value: '-'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        beforeactivate: 'onPanelBeforeActivate',
                        beforedeactivate: 'stopTask',
                        removed: 'onPanelRemoved'
                    }
                },
                {
                    xtype: 'TrafficView'
                }
            ]
        }
    ],

    onPanelBeforeActivate: function(component, eOpts) {
          this.startTask();
    },

    stopTask: function(component, eOpts) {
        if (this.task) {
            Ext.TaskManager.stop(this.task);
        }
    },

    onPanelRemoved: function(component, ownerCt, eOpts) {
        this.stopTask();
    },

    startTask: function() {
        var me = this, form;
        var s = Ext.create('app.store.StoreSystemInfo');

        var task = me.task = {
            run: function(){
                s.load({callback:function(r){
                    if (me && (form = me.down('form')) && r.length) {
                        form.loadRecord(r[0]);
                    }
                }});
            },
            interval: 3000
        };
        task.run();
        Ext.TaskManager.start(task);
    }

});