/*
 * File: app/view/ToolView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.ToolView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ToolView',

    requires: [
        'app.view.ToolsViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    viewModel: {
        type: 'toolsview'
    },
    title: '实用工具',

    items: [
        {
            xtype: 'tabpanel',
            margin: 10,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'DIG',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            jsonSubmit: true,
                            url: '../tool/dig',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'DIG域名',
                                    name: 'domain',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: '查询类型',
                                    name: 'type',
                                    allowBlank: false,
                                    queryMode: 'local',
                                    store: 'StoreRType'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'DNS服务器',
                                    name: 'dnsserver',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    fieldLabel: '跟踪查询',
                                    name: 'trace',
                                    boxLabel: '开启'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var Valid = this.up("form").getForm().isValid();
                                        if (!Valid) return;

                                        this.up("form").getForm().submit({
                                            waitMsg: '正在查询',
                                            success: function (form, action) {
                                                this.result.setValue(action.result.msg);
                                            },
                                            failure: function (form, action) {
                                                Ext.Msg.alert('失败', action.result.msg);
                                            },
                                            scope: {
                                                result:  this.up("form").query("[id=result]")[0]
                                            }
                                        });
                                    },
                                    text: '查询'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 400,
                                    id: 'result',
                                    fieldLabel: '结果',
                                    labelAlign: 'top',
                                    submitValue: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'WHOIS',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            jsonSubmit: true,
                            url: '../tool/whois',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '域名',
                                    name: 'domain',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var Valid = this.up("form").getForm().isValid();
                                        if (!Valid) return;

                                        this.up("form").getForm().submit({
                                            waitMsg: '正在查询',
                                            success: function (form, action) {
                                                this.result.setValue(action.result.msg);
                                            },
                                            failure: function (form, action) {
                                                Ext.Msg.alert('失败', action.result.msg);
                                            },
                                            scope: {
                                                result:  this.up("form").query("[id=whoisresult]")[0]
                                            }
                                        });
                                    },
                                    text: '查询'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 400,
                                    id: 'whoisresult',
                                    fieldLabel: '结果',
                                    labelAlign: 'top',
                                    submitValue: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'PING',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            jsonSubmit: true,
                            url: '../tool/ping',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '域名或主机',
                                    name: 'domain',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var Valid = this.up("form").getForm().isValid();
                                        if (!Valid) return;

                                        this.up("form").getForm().submit({
                                            waitMsg: '正在查询',
                                            success: function (form, action) {
                                                this.result.setValue(action.result.msg);
                                            },
                                            failure: function (form, action) {
                                                Ext.Msg.alert('失败', action.result.msg);
                                            },
                                            scope: {
                                                result:  this.up("form").query("[id=pingresult]")[0]
                                            }
                                        });
                                    },
                                    text: '查询'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    height: 400,
                                    id: 'pingresult',
                                    fieldLabel: '结果',
                                    labelAlign: 'top',
                                    submitValue: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'NTP',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            jsonSubmit: true,
                            url: '../tool/ntp',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'NTP 服务器',
                                    name: 'ntpserver',
                                    value: 'pool.ntp.org',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var Valid = this.up("form").getForm().isValid();
                                        if (!Valid) return;

                                        this.up("form").getForm().submit({
                                            waitMsg: '正在查询',
                                            success: function (form, action) {
                                                this.result.setValue(action.result.msg);
                                            },
                                            failure: function (form, action) {
                                                Ext.Msg.alert('失败', action.result.msg);
                                            },
                                            scope: {
                                                result:  this.up("form").query("[id=ntpresult]")[0]
                                            }
                                        });
                                    },
                                    text: '查询'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    id: 'ntpresult',
                                    fieldLabel: '结果',
                                    labelAlign: 'top',
                                    submitValue: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '转码工具',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            header: false,
                            title: 'My Form',
                            jsonSubmit: true,
                            url: '../tool/code',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: '输入字符串',
                                    name: 'text',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'radiogroup',
                                    width: 400,
                                    fieldLabel: ' ',
                                    labelSeparator: ' ',
                                    allowBlank: false,
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'method',
                                            boxLabel: '转为Punycode',
                                            checked: true,
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'method',
                                            boxLabel: '转为中文',
                                            inputValue: '2'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var Valid = this.up("form").getForm().isValid();
                                        if (!Valid) return;

                                        this.up("form").getForm().submit({
                                            waitMsg: '正在查询',
                                            success: function (form, action) {
                                                this.result.setValue(action.result.msg);
                                            },
                                            failure: function (form, action) {
                                                Ext.Msg.alert('失败', action.result.msg);
                                            },
                                            scope: {
                                                result:  this.up("form").query("[id=coderesult]")[0]
                                            }
                                        });
                                    },
                                    text: '查询'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'coderesult',
                                    fieldLabel: '结果',
                                    submitValue: false
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});