/*
 * File: app/view/UsermgrView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.UsermgrView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.UsermgrView',

    requires: [
        'app.view.UsermgrViewViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.grid.column.Action'
    ],

    viewModel: {
        type: 'usermgrview'
    },
    itemId: 'usermgr',
    title: '用户管理',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    text: '添加用户'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            title: 'My Grid Panel',
            store: 'StoreUser',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userName',
                    text: '用户名'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'email',
                    text: '邮箱'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'createTime',
                    text: '创建时间'
                },
                {
                    xtype: 'actioncolumn',
                    emptyCellText: '操作',
                    items: [
                        {

                        }
                    ]
                }
            ]
        }
    ]

});