/*
 * File: app/model/General.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.General', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'string',
            name: 'HOST_NAME'
        },
        {
            type: 'string',
            name: 'DOMAIN_NAME'
        },
        {
            type: 'string',
            name: 'WEB_PROTOCOL'
        },
        {
            type: 'string',
            name: 'WEB_PORT'
        },
        {
            type: 'string',
            name: 'LOGIN_TYPE'
        },
        {
            type: 'string',
            name: 'TIME'
        },
        {
            type: 'string',
            name: 'TIME_ZONE'
        },
        {
            type: 'string',
            name: 'NTP'
        },
        {
            type: 'string',
            name: 'NTP_SERVER'
        },
        {
            type: 'string',
            name: 'LOG_FIREWALL'
        },
        {
            type: 'string',
            name: 'LOG_DNS'
        },
        {
            type: 'string',
            name: 'LOG_SYSTEM'
        }
    ]
});