/*
 * File: app/model/RecordModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.RecordModel', {
    extend: 'Ext.data.Model',
    alias: 'model.RecordModel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'ID'
        },
        {
            type: 'string',
            name: 'RecordTitle'
        },
        {
            type: 'int',
            name: 'TTL'
        },
        {
            type: 'string',
            name: 'IN'
        },
        {
            type: 'string',
            name: 'Type'
        },
        {
            type: 'string',
            name: 'Priority'
        },
        {
            type: 'string',
            name: 'Value'
        }
    ]
});