/*
 * File: app/model/RouteModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.RouteModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'route'
        },
        {
            type: 'string',
            name: 'eth'
        },
        {
            type: 'string',
            name: 'gateway'
        },
        {
            type: 'string',
            name: 'ip'
        },
        {
            type: 'int',
            name: 'mask'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'int',
            name: 'enabled'
        },
        {
            type: 'string',
            name: 'memo'
        }
    ]
});