/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.controller.MainController', {
    extend: 'Ext.app.Controller',

    refs: {
        content: 'panel#contentPanel'
    },

    init: function(application) {
        this.control({
            "menuitem": {
                click: this.changeview
            },
        });
    },

    changeview: function(menuitem) {
        var layout = this.getContent().getLayout();
        var cardid = 0;
        if (menuitem.id =="networkcfg")
        {
            cardid=5;
        }
        if (menuitem.id =="routermgr")
        {
            cardid=6;
        }
        if (menuitem.id =="domainmgr")
        {
            cardid=1;
        }

        if (menuitem.id =="dnslog")
        {
            cardid=2;
        }


        if (menuitem.id =="tools")
        {
            cardid=3;
        }
        if (menuitem.id =="systeminfo")
        {
             cardid=4;
        }
        layout.setActiveItem(cardid);
    }

});
